### ISSUE TITLE
isJustDown not registering very first press

### ISSUE THREAD

**Issue by pmuren** [ehgoodenough/keyb#1]
Noticed that isJustDown is not firing until I have already pressed the associated key (shift, in my case) once.

**Comment by ehgoodenough** [comment]
The issue is fixed with our newest version, v1.1.0! Now with optional deltas. Thank you!

**Comment by ehgoodenough** [comment]
The fix: https://github.com/ehgoodenough/keyb/commit/7b52620f2d77271909330fa7a10fc07d90a03c76
